//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlitetest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sqlitetest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Соколова Ульяна Леонидовна,Толочко Юнона Артёмовна,Шевченко Прасковья Максимовна,Легойда Федосья Романовна,Савина Йосифа Даниловна,Семёнова Шанетта Станиславовна,Карпова Эсмеральда Леонидовна,Панова Инесса Ярославовна,Аксёнова Цара Вадимовна,Трублаевска Федосья Даниловна,Федункив Харита Вадимовна,Ефремова Йосифа Григорьевна,Ефимова Жозефина Фёдоровна,Быкова Ядвига Артёмовна,Хохлова Георгина Фёдоровна,Авдеева Зинаида Сергеевна,Повалий Юнона Платоновна,Кудряшова Елизавета Григорьевна,Гусева Йоханна Станислав [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIOf {
            get {
                return ResourceManager.GetString("FIOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Ершов Эдуард Брониславович,Давыдов Харитон Брониславович,Петровский Лаврентий Эдуардович,Федосеев Дмитрий Виталиевич,Юдин Никита Викторович,Житар Виктор Юхимович,Горшков Огюст Александрович,Фёдоров Осип Станиславович,Галкин Жерар Романович,Осипов Нестор Сергеевич,Морозов Трофим Андреевич,Логинов Руслан Леонидович,Иващенко Филипп Львович,Капустин Эдуард Станиславович,Сысоев Тимур Брониславович,Емельянов Эрик Юхимович,Полищук Захар Юхимович,Фомин Еремей Михайлович,Петров Чарльз Эдуардович,Павлив Устин Михайл [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIOm {
            get {
                return ResourceManager.GetString("FIOm", resourceCulture);
            }
        }
    }
}
